name: Exploring Workflow Dispatch Trigger

on:
  workflow_dispatch:
     inputs:
      run-job:
        description: "Run specific job"
        type: boolean
        required: false
      custom_messages:
          description: enter a custom message 
          type: string
          required: true



jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Exploring Workflow Dispatch Trigger"
  job2:                                       #added
    runs-on: ubuntu-latest
    steps:
      - name: Printing Custom Message
        run: echo ${{ inputs.custom_message }} #end